---
secrets:
  DB_PASSWORD: 'Password for PostgreSQL service (moviepass)'
  ADMIN_PASSWORD: 'Admin user password for application'
  SLACK_WEBHOOK_URL: >
    Webhook URL for Slack notifications
    (if used)
