---
blank_issues_enabled: false
contact_links:
  - name: 💬 Discussions
    url: https://github.com/Jalez/movie-management-api/discussions
    about: Ask questions and discuss ideas with the community
