name: CI/CD Pipeline

permissions:
  contents: read
  security-events: write

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build-and-test:
    uses: ./.github/workflows/reusable-steps.yml
    with:
      job: build-and-test
    secrets:
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}

  quality-checks:
    needs: build-and-test
    uses: ./.github/workflows/reusable-steps.yml
    with:
      job: quality-checks

  docker-build:
    needs: build-and-test
    if: github.event_name == 'push' && github.ref =~ 'refs/heads/(main|develop)'
    uses: ./.github/workflows/reusable-steps.yml
    with:
      job: docker-build

  security-scan:
    needs: build-and-test
    uses: ./.github/workflows/reusable-steps.yml
    with:
      job: security-scan

  notify:
    needs:
      - build-and-test
      - quality-checks
      - docker-build
      - security-scan
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Notify on failure
        if: failure()
        run: |
          echo "❌ CI/CD Pipeline failed!"
          echo "See details: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
      - name: Notify on success
        if: success()
        run: |
          echo "✅ CI/CD Pipeline completed successfully!"
          echo "Artifacts & reports are in this run."